### ISSUE TITLE
Feature Request: Implement authorization flow for Service Accounts

### ISSUE THREAD

**Issue by dermesser** [Byron/yup-oauth2#26]
The flow is described here: https://developers.google.com/identity/protocols/OAuth2ServiceAccount. It is especially interesting/necessary for Google Cloud Platform services, such as Cloud Pub/Sub, Compute Engine, Cloud Storage, etc.

tl;dr:

* Get a Service Account key from the developer console
* Sign a *claim set* (containing scope, app ID, ...) with that key, resulting in a *JWT* (JSON web token)
* Request a token from https://www.googleapis.com/oauth2/v4/token using the signed JWT
* Use the token; refresh if needed using the JWT.

The difficult part is probably generating the JWT signature, but it seems that https://crates.io/crates/jwt will do that for us.

I'll probably start working on this in the next few weeks, depending on the weather :o) (I'm posting this here just in case you or someone else wants to work on it or is already on it)

**Comment by Byron** [comment]
Thanks @dermesser ! It's quite fantastic to see you contributing so much ! And with these contributions, all programs/libraries generated with `google-apis-rs` profit right away.

Do you think that with that planned contribution, the oauth implementation is feature-complete ? If so, we could consider jumping to version 1.0 and keep the current API for good. Something else we might consider is renaming the project, just because `yup` stands for `youtube uploader`, coming from times when this crate was solely to be a minimal oauth implementation needed to make youtube uploads work.

I'd be happy to hear your thoughts.

**Comment by Byron** [comment]
@dermesser That one seems fixed now, isn't it?

**Comment by dermesser** [comment]
Yes!
